Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "win2008r2"
  c.vm.communicator = "winrm"
  c.vm.network(:private_network, {:ip=>"192.168.33.22"})
  c.vm.network(:forwarded_port, {:guest=>5985, :host=>5985, :id=>"winrm", :auto_correct=>true})
  c.vm.network(:forwarded_port, {:guest=>3391, :host=>33391})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
