Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "win2k8r2"
  c.vm.communicator = "winrm"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "C:/Users/rle0401/.kitchen/cache", "$env:TEMP\omnibus\cache", create: true
  c.vm.provider :virtualbox do |p|
  end
end
